#
# Authors
#   github.com/luncliff	(dh.park@alcherainc.com)
#
language: go

git:
  quiet: true
  submodules: true
  depth: 3

go: "1.11"

install:
 - go version
 - go env

script:
 - go test -cover -v

matrix:
  # allow_failures:
  #   - os: windows
  include:
    - name: Go 1.11 Mac OS
      os: osx
    - name: Go 1.11 Linux
      os: linux
      dist: xenial
    - name: Go 1.11 Windows
      os: windows
